if ((typeof(basis$0IO$1)) == "undefined") {basis$0IO$1 = {};
};
(function(){basis$0IO$1.eq_buffer_mode$89 = function(v$91,v$92){switch (v$91) { case 0: {switch (v$92) { case 0: {return true;
 break; }default: {return false;
} };
 break; }case 1: {switch (v$92) { case 1: {return true;
 break; }default: {return false;
} };
 break; }case 2: {switch (v$92) { case 2: {return true;
 break; }default: {return false;
} };
 break; } };
};
basis$0IO$1.en$Io$55 = new String("Io");
basis$0IO$1.en$BlockingNotSupported$56 = new String("BlockingNotSupported");
basis$0IO$1.exn$BlockingNotSupported$56 = [basis$0IO$1.en$BlockingNotSupported$56];
basis$0IO$1.en$NonblockingNotSupported$57 = new String("NonblockingNotSupported");
basis$0IO$1.exn$NonblockingNotSupported$57 = [basis$0IO$1.en$NonblockingNotSupported$57];
basis$0IO$1.en$RandomAccessNotSupported$58 = new String("RandomAccessNotSupported");
basis$0IO$1.exn$RandomAccessNotSupported$58 = [basis$0IO$1.en$RandomAccessNotSupported$58];
basis$0IO$1.en$ClosedStream$59 = new String("ClosedStream");
basis$0IO$1.exn$ClosedStream$59 = [basis$0IO$1.en$ClosedStream$59];
return 0;
})();
